"use client";

import { useInView } from "react-intersection-observer";
import { cn } from "@/lib/utils";
import { Info } from "lucide-react";

interface TermsParticipationProps {
  onVisible: (id: string) => void;
}

export default function TermsParticipation({ onVisible }: TermsParticipationProps) {
  const { ref, inView } = useInView({
    triggerOnce: false,
    threshold: 0.2,
    onChange: (visible) => {
      if (visible) onVisible("participation");
    },
  });

  return (
    <section
      id="participation"
      ref={ref}
      className={cn(
        "scroll-mt-32 transition-all duration-700 ease-out",
        inView ? "opacity-100 translate-y-0" : "opacity-0 translate-y-6"
      )}
    >
      <h2 className="text-2xl font-bold text-primary-deep mb-5">
        4. Participation &amp; Surplus
      </h2>

      {/* In Plain English callout */}
      <div className="border-l-4 border-primary bg-primary/5 rounded-r-lg p-4 mb-5">
        <div className="flex items-center gap-2 mb-1.5">
          <Info className="w-3.5 h-3.5 text-primary" />
          <span className="text-[10px] font-bold tracking-widest text-primary uppercase">
            In Plain English
          </span>
        </div>
        <p className="text-muted-foreground text-sm leading-relaxed italic">
          Earnings come from real-world taxi and delivery rides. Because traffic
          and demand change every day, your daily surplus (payout) will vary. We
          cannot guarantee a fixed return because this is a real business
          operation, not a bank account.
        </p>
      </div>

      <p className="text-muted-foreground leading-relaxed text-sm mb-4">
        Participation involves contributing to the operational capacity of the
        RT Mobility fleet. &quot;Surplus&quot; refers to the net operational revenue
        generated by fleet assets after all operational costs, insurance
        premiums, and maintenance reserves have been deducted.
      </p>

      <p className="text-muted-foreground leading-relaxed text-sm">
        Surplus distributions are calculated based on daily utilization rates.{" "}
        <strong className="text-primary-deep">
          RT Mobility does not guarantee a fixed rate of return.
        </strong>{" "}
        All distributions are contingent upon the successful real-world
        operation of physical assets in competitive markets.
      </p>
    </section>
  );
}
